apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmaps.yaml
  - backend-api.yaml
  - dashboard-react.yaml
  - dashboard-streamlit.yaml
  - ingress.yaml
