apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-backend-config
  namespace: telemetry-agent
data:
  APP_ENV: "local"
  DATA_SOURCE: "sample"
  LOG_LEVEL: "DEBUG"
  REFERENCE_DIR: "/app/data/reference"
  SAMPLE_DATA_FILE: "/app/data/sample/sample_vin_data.json"
  FEATURE_LANGGRAPH: "false"
  FEATURE_GENAI: "true"
